version: '3.1'

services:
  app:
    image: node:12-alpine
    container_name: gobarber-app
    ports:
      - "3333:3333"
    command: sh -c "yarn && yarn typeorm migration:run && yarn dev:server"
    working_dir: /app
    volumes:
      - ".:/app"

  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: gobarber
    ports:
      - "5432:5432"
    container_name: gobarber-db
